// <auto-generated />
using System;
using Cremory.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cremory.API.Migrations
{
    [DbContext(typeof(CremoryDbContext))]
    [Migration("20260720081646_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Cremory.API.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("KEY");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VALUE");

                    b.HasKey("Key");

                    b.ToTable("APP_SETTINGS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DISPLAY_ORDER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.HasKey("CategoryId");

                    b.ToTable("CATEGORIES", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.DeviceToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TOKEN_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("LAST_USED_AT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("PLATFORM");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("TOKEN");

                    b.HasKey("TokenId");

                    b.ToTable("DEVICE_TOKENS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ORDER_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CustomerContact")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUSTOMER_CONTACT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<string>("DeliveryType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("DELIVERY_TYPE");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_ARCHIVED");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ITEMS");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("PAYMENT_STATUS");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("SOURCE");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("TOTAL_PRICE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("OrderId");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<string>("AddOnDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ADD_ON_DESCRIPTION");

                    b.Property<decimal?>("AddOnPricePerUnit")
                        .HasColumnType("TEXT")
                        .HasColumnName("ADD_ON_PRICE_PER_UNIT");

                    b.Property<bool>("AutoDeduct")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AUTO_DEDUCT");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("BASE_PRICE");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CURRENT_STOCK");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DISPLAY_ORDER");

                    b.Property<string>("Flavor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("FLAVOR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LOW_STOCK_THRESHOLD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("UNIT");

                    b.Property<string>("Variant")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("VARIANT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Product", b =>
                {
                    b.HasOne("Cremory.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
