// <auto-generated />
using System;
using Cremory.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cremory.API.Migrations
{
    [DbContext(typeof(CremoryDbContext))]
    [Migration("20260704133040_AddProductStock")]
    partial class AddProductStock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Cremory.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DISPLAY_ORDER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.HasKey("CategoryId");

                    b.ToTable("CATEGORIES", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("INGREDIENT_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("REORDER_LEVEL");

                    b.Property<decimal>("StockQuantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("STOCK_QUANTITY");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("UNIT");

                    b.HasKey("IngredientId");

                    b.ToTable("INGREDIENTS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ORDER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CustomerContact")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUSTOMER_CONTACT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("ITEMS");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("SOURCE");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("TOTAL_PRICE");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("UPDATED_AT");

                    b.HasKey("OrderId");

                    b.ToTable("ORDERS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<string>("AddOnDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ADD_ON_DESCRIPTION");

                    b.Property<decimal?>("AddOnPricePerUnit")
                        .HasColumnType("TEXT")
                        .HasColumnName("ADD_ON_PRICE_PER_UNIT");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("BASE_PRICE");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CURRENT_STOCK");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DISPLAY_ORDER");

                    b.Property<string>("Flavor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("FLAVOR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LOW_STOCK_THRESHOLD");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<string>("Variant")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("VARIANT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RECIPE_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("TEXT")
                        .HasColumnName("SELLING_PRICE");

                    b.HasKey("RecipeId");

                    b.ToTable("RECIPES", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RECIPE_INGREDIENT_ID");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("INGREDIENT_ID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("QUANTITY");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RECIPE_ID");

                    b.HasKey("RecipeIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RECIPE_INGREDIENTS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("USER_ID");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("ACCOUNT_TYPE");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("CONTACT_NUMBER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.HasKey("UserId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("Cremory.API.Models.Product", b =>
                {
                    b.HasOne("Cremory.API.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Cremory.API.Models.RecipeIngredient", b =>
                {
                    b.HasOne("Cremory.API.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cremory.API.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Cremory.API.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
