
using Microsoft.EntityFrameworkCore;
using Cremory.API.Data;
using Cremory.API.Hubs;
using Cremory.API.Models;
using Cremory.API.Services;

namespace Cremory.API
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            builder.Services.AddControllers();
            builder.Services.AddDbContext<Cremory.API.Data.CremoryDbContext>(options =>
            {
                if (builder.Environment.IsDevelopment())
                    options.UseSqlite("Data Source=cremory.db");
                else
                    options.UseNpgsql(
                        Environment.GetEnvironmentVariable("DATABASE_URL")
                        ?? builder.Configuration.GetConnectionString("PostgresConnection"));
            });
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen();
            builder.Services.AddSignalR();
            builder.Services.Configure<OrderParserOptions>(
                builder.Configuration.GetSection(OrderParserOptions.SectionName));
builder.Services.Configure<MessengerOptions>(options =>
{
    options.VerifyToken = Environment.GetEnvironmentVariable("MESSENGER_VERIFY_TOKEN")
        ?? builder.Configuration.GetSection(MessengerOptions.SectionName)["VerifyToken"] ?? "";
    options.PageAccessToken = Environment.GetEnvironmentVariable("MESSENGER_PAGE_ACCESS_TOKEN")
        ?? builder.Configuration.GetSection(MessengerOptions.SectionName)["PageAccessToken"] ?? "";
    options.AppSecret = Environment.GetEnvironmentVariable("MESSENGER_APP_SECRET")
        ?? builder.Configuration.GetSection(MessengerOptions.SectionName)["AppSecret"] ?? "";
});
            builder.Services.AddScoped<OrderParserService>();
            builder.Services.AddScoped<FcmNotificationService>();

            builder.Services.AddCors(options =>
            {
                options.AddDefaultPolicy(policy =>
                    policy.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());
            });

            var app = builder.Build();

            FcmNotificationService.InitializeFirebase(app.Environment);

            using (var scope = app.Services.CreateScope())
            {
                var db = scope.ServiceProvider.GetRequiredService<CremoryDbContext>();
                if (db.Database.IsRelational())
                {
                    try
                    {
                        db.Database.ExecuteSqlRaw("ALTER TABLE \"PRODUCTS\" ADD COLUMN IF NOT EXISTS \"UNIT\" varchar(20) NULL");
                        db.Database.ExecuteSqlRaw("ALTER TABLE \"PRODUCTS\" ADD COLUMN IF NOT EXISTS \"AUTO_DEDUCT\" boolean NOT NULL DEFAULT TRUE");
                        db.Database.ExecuteSqlRaw("ALTER TABLE \"PRODUCTS\" ADD COLUMN IF NOT EXISTS \"CURRENT_STOCK\" integer NOT NULL DEFAULT 0");
                        db.Database.ExecuteSqlRaw("ALTER TABLE \"PRODUCTS\" ADD COLUMN IF NOT EXISTS \"LOW_STOCK_THRESHOLD\" integer NOT NULL DEFAULT 10");

                        db.Database.ExecuteSqlRaw("ALTER TABLE \"ORDERS\" ADD COLUMN IF NOT EXISTS \"IS_ARCHIVED\" boolean NOT NULL DEFAULT FALSE");
                        db.Database.ExecuteSqlRaw("ALTER TABLE \"ORDERS\" ADD COLUMN IF NOT EXISTS \"DELIVERY_TYPE\" varchar(20) NULL");
                        db.Database.ExecuteSqlRaw("ALTER TABLE \"ORDERS\" ADD COLUMN IF NOT EXISTS \"PAYMENT_STATUS\" varchar(20) NULL");
                        db.Database.ExecuteSqlRaw("ALTER TABLE \"ORDERS\" ADD COLUMN IF NOT EXISTS \"ADDRESS\" varchar(500) NULL");

                        db.Database.ExecuteSqlRaw("""
                            CREATE TABLE IF NOT EXISTS "DEVICE_TOKENS" (
                                "DEVICE_TOKEN_ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "TOKEN" varchar(500) NOT NULL,
                                "DEVICE_NAME" varchar(100) NULL,
                                "CREATED_AT" timestamp with time zone NOT NULL DEFAULT NOW()
                            )
                            """);
                        db.Database.ExecuteSqlRaw("""
                            DROP TABLE IF EXISTS "USERS" CASCADE
                            """);
                        db.Database.ExecuteSqlRaw("""
                            CREATE TABLE "USERS" (
                                "UserId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "Username" varchar(100) NOT NULL,
                                "PasswordHash" text NOT NULL,
                                "DisplayName" varchar(200) NOT NULL DEFAULT '',
                                "Role" varchar(20) NOT NULL DEFAULT 'staff',
                                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
                            )
                            """);
                        db.Database.ExecuteSqlRaw("""
                            CREATE TABLE IF NOT EXISTS "APP_SETTINGS" (
                                "KEY" varchar(100) PRIMARY KEY,
                                "VALUE" text NULL
                            )
                            """);
                        Console.WriteLine("Schema sync completed");
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"Schema sync failed: {ex.Message}");
                    }
                }

                try { DbInitializer.Seed(db); }
                catch (Exception ex) { Console.WriteLine($"Seeding failed: {ex.Message}"); }
            }

            app.Use(async (context, next) =>
            {
                var sw = System.Diagnostics.Stopwatch.StartNew();
                await next();
                sw.Stop();
                var statusCode = context.Response.StatusCode;
                var method = context.Request.Method;
                var path = context.Request.Path;
                Console.WriteLine($"{method} {path} -> {statusCode} ({sw.ElapsedMilliseconds}ms)");
            });

            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseCors();
            app.UseAuthorization();
            app.MapControllers();
            app.MapHub<OrderHub>("/hubs/orders");

            app.Run();
        }
    }
}

